port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090

proxies:
  # 脚本会自动填充这里

proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - DIRECT
  
  - name: 🇺🇳所有-自动
    type: url-test
    include-all: true
    tolerance: 50
    interval: 360
    
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - DIRECT   
  - name: Ads
    type: select
    proxies:
      - Reject
rules:
  - DOMAIN-SUFFIX,google.com,🚀 节点选择
  - DOMAIN-KEYWORD,github,🚀 节点选择
  - GEOIP,CN,DIRECT

  - MATCH,🐟 漏网之鱼

